### ISSUE TITLE
While running the code in for loop after the first execution all the other textboxes are moving up, how should i handle this?

### ISSUE THREAD

**Issue by ronnygala** [NikolaiMe/textbox-for-pdfkit#9]

**Comment by NikolaiMe** [comment]
Sorry I don't know what you are doing. Please provide a decent description of what you are doing and what issues you are encountering. Also a descriptive code - snipped would help. Without that I don't think I can help you.

**Comment by NikolaiMe** [comment]
As no detailed description of the issue was provided, this issue is closed.
